"""Initial schema with tasks, environments, events, AI sessions

Revision ID: edf7666e0198
Revises: 
Create Date: 2026-03-15 13:41:40.401179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf7666e0198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_path', sa.String(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RADAR', 'RUNWAY', 'FLIGHT', 'BLOCKED', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('location_tags', sa.JSON(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_code'), 'tasks', ['task_code'], unique=True)
    op.create_table('ai_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'ACTION_REQUIRED', 'COMPLETE', name='aisessionstatus'), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_sessions_task_id'), 'ai_sessions', ['task_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_SPLIT', 'TASK_MOVED', 'TASK_DONE', 'TASK_BLOCKED', 'TASK_TAGGED', 'TASK_PRIORITIZED', name='taskeventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('task_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_paths_task_id'), 'task_paths', ['task_id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('log_message', sa.String(), nullable=False),
    sa.Column('log_level', sa.Enum('INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_session_id'), 'ai_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_logs_session_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_task_paths_task_id'), table_name='task_paths')
    op.drop_table('task_paths')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_ai_sessions_task_id'), table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_index(op.f('ix_tasks_task_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
